import * as React from 'react';
import Helmet from 'react-helmet';
import { css } from '@emotion/core';

import Wrapper from '../components/Wrapper';
import IndexLayout from '../layouts';
import SiteNav from '../components/header/SiteNav';
import { SiteHeader, outer, inner, SiteMain } from '../styles/shared';
import SocialLinks from '../components/header/SocialLinks';
import { colors } from '../styles/colors';

const PageTemplate = css`
  .site-main {
    background: #fff;
    padding-bottom: 4vw;
  }
`;

const PrivacyPolicy: React.FC = () => {
  return (
    <IndexLayout>
      <Helmet>
        <title>About</title>
      </Helmet>
      <Wrapper css={PageTemplate}>
        <header
          css={[outer, SiteHeader]}
          style={{
            background: `linear-gradient(${colors.iceberg}, #fff 80%)`,
          }}
        >
          <div css={inner}>
            <SiteNav />
            <SocialLinks />
          </div>
        </header>
        <main id="site-main" className="site-main" css={[SiteMain, outer]}>
          <div css={inner}>
            <h1>Privacy Policy </h1>
            <p>
              We are committed to ensuring that your privacy is protected and we shall endeavour to
              use any information that you provide when using this website in accordance with this
              privacy policy.
            </p>
            <h2>Personal Information</h2>
            <p>
              When you visit the Site, we automatically collect certain information about your
              device, including information about your web browser, IP address, time zone, and some
              of the cookies that are installed on your device. Additionally, as you browse the
              Site, we collect information about the individual web pages or products that you view,
              what websites or search terms referred you to the Site, and information about how you
              interact with the Site. We refer to this automatically-collected information as
              “Device Information.” We collect Device Information using the following technologies:
              <h3>Log Files</h3> Our systems automatically gather some anonymous information about
              visitors, including IP addresses, browser type, language, and the times and dates of
              webpage visits. The data collected does not include personally identifiable
              information and is used, as described above, for statistical analysis, to understand
              user behaviour, and to administer the site.
              <h3>Cookies</h3>
              Cookies are text files stored on your computer, and accessible only to the websites
              which create them. Our website may from time to time use cookies and log files for
              statistical analysis, to understand user behaviour, to administer the site, to tailor
              the information presented to a user based on their preferences, and to improve user
              experience. Any information gathered by our use of cookies is compiled on an
              aggregate, anonymous basis.
              <h3> GoogleAnalytics </h3>
              Our website uses Google Analytics, a web analytics service provided by Google, Inc.
              ("Google"). The information generated by the cookie about your use of our website
              (including your IP address) will be transmitted to and stored by Google on servers in
              the United States. Google will use this information for the purpose of evaluating your
              use of our website, compiling reports on website activity for website operators and
              providing other services relating to website activity and internet usage. Google may
              also transfer this information to third parties where required to do so by law, or
              where such third parties process the information on Google’s behalf. Google will not
              associate your IP address with any other data held by Google. You can read more about
              how Google uses your Personal Information here:
              <a href="https://www.google.com/intl/en/policies/privacy/">
                https://www.google.com/intl/en/policies/privacy/
              </a>
              . You can also opt-out of Google Analytics here:{' '}
              <a href="https://tools.google.com/dlpage/gaoptout">
                https://tools.google.com/dlpage/gaoptout
              </a>
              .
            </p>
            <h2>Third Party Privacy Policies</h2>
            You should consult the respective privacy policies of these third-party websites for
            more detailed information on their practices as well as for instructions about how to
            opt-out of certain practices. SkillfullyTangled’s privacy policy does not apply to, and
            we cannot control the activities of, such other advertisers or web sites.
            <h2>Our Advertising Partners</h2>
            Some of our advertising partners may use cookies and web beacons on our site. Our
            advertising partners include:
            <ul>
              <li>Google</li> <li>Amazon</li> <li>ShareASale</li>
            </ul>
            These third-party ad servers or ad networks use technology in their respective
            advertisements and links that appear on this site and which are sent directly to your
            browser. They automatically receive your IP address when this occurs. Other technologies
            (such as cookies, JavaScript, or Web Beacons) may also be used by our site’s third-party
            ad networks to measure the effectiveness of their advertising campaigns and/or to
            personalize the advertising content that you see on the site. SkillfullyTangled has no
            access to or control over these cookies that are used by third-party advertisers.
            <h2>Your Rights</h2>
            <p>
              If you are a European resident, you have the right to access personal information we
              hold about you and to ask that your personal information be corrected, updated, or
              deleted. If you would like to exercise this right, please contact us through the
              contact information below. Additionally, if you are a European resident we note that
              we are processing your information in order to fulfill contracts we might have with
              you (for example if you make an order through the Site), or otherwise to pursue our
              legitimate business interests listed above. Additionally, please note that your
              information will be transferred outside of Europe, including to Canada and the United
              States.
            </p>
            <h2>Data Retention</h2>
            <p>
              When you place an order through the Site, we will maintain your Order Information for
              our records unless and until you ask us to delete this information.
            </p>
            <h2>Changes</h2>
            <p>
              We may update this privacy policy from time to time in order to reflect, for example,
              changes to our practices or for other operational, legal or regulatory reasons.
            </p>
            <h2>Consent</h2>
            By using our website, you hereby consent to our privacy policy and agree to its terms.
            <h2>Contact Us</h2>
            <p>
              For more information about our privacy practices, if you have questions, or if you
              would like to make a complaint, please contact us by e-mail at
              skillfullytangled@gmail.com.
            </p>
          </div>
        </main>
      </Wrapper>
    </IndexLayout>
  );
};

export default PrivacyPolicy;
